baseURL = 'https://www.writingquests.org/'
languageCode = 'en-us'
title = 'Writing Quests'
theme = 'wordsmith'

[markup.goldmark.parser.attribute]
block = true # default is false

[params]
    [params.homepage]
      logo = "images/logo2024.svg"
      rss = "https://writingquests.substack.com/feed.xml"
      twitter = "https://x.com/writingquests"
      pinterest = "https://pinterest.com/WritingQuests/"
      instagram = "https://instagram.com/writingquests"
      facebook = "https://facebook.com/groups/writingquests"
      youtube = "https://www.youtube.com/channel/UCGNbZWYi4pTkENOYYLgtCvg"
      calendar = "https://calendar.google.com/calendar/embed?src=ef1f8f146ebcac42b495cdc97fe11f1a5d102695cd12cc5ceb76fec5987c9afd%40group.calendar.google.com&ctz=UTC"
      contact = "https://docs.google.com/forms/d/e/1FAIpQLSdgVgL2yTOYHUM9SJ379OHzzOTCwclUr4wNmBawq_fvIZcLNA/viewform?embedded=true"
      help = "https://docs.google.com/forms/d/e/1FAIpQLSdE1IFm3SlGAf4bkWeriH3uFDLc6KxqMGfLUw9jCV-emsytDg/viewform?embedded=true"
    [params.meta]
      favicon = "1"


[menu]
  [[menu.main]]
    name = 'about'
    pageRef = '/about/'
    weight = 20

  [[menu.main]]
    name = 'about writing quests'
    pageRef = '/about/'
    parent = 'about'
    weight = 25

  [[menu.main]]
    name = 'mission, vision, & values'
    pageRef = '/mission/'
    parent = 'about'
    weight = 23

  [[menu.main]]
    name = 'data privacy'
    pageRef = '/cla-privacy-policy/'
    parent = 'about'
    weight = 20

  [[menu.main]]
    name = 'framework'
    pageRef = '/framework/'
    weight = 20

  [[menu.main]]
    name = 'blog'
    pageRef = '/blog/'
    weight = 20

  [[menu.main]]
    name = 'contact us'
    pageRef = '/contact/'
    weight = 20

  [[menu.main]]
    name = 'get involved'
    pageRef = '/get-involved/'
    weight = 20

  [[menu.main]]
    name = 'help out'
    parent = 'get involved'
    pageRef = '/get-involved/help/'
    weight = 20

  [[menu.main]]
    name = 'contributors'
    parent = 'get involved'
    pageRef = '/get-involved/contributors/'
    weight = 20

# LATER   [[menu.main]]
# LATER     name = 'quests'
# LATER     parent = 'get involved'
# LATER     pageRef = '/get-involved/quests.md'
# LATER     weight = 20

  [[menu.main]]
    name = 'assets and resources'
    parent = 'get involved'
    pageRef = '/get-involved/assets-and-resources.md'
    weight = 20

